package enums;

public enum Action {
	MOVE, REGISTER, SIGNUP, ACCESS, SIGNIN, LIST, CUST_RETRIEVE, CUST_UPDATE_PAGE, CUST_FILE_UPLOAD, CUST_DELETE, PROD_LIST, PROD_RETRIEVE, PROD_FILE_UPLOAD, PROD_UPDATE_PAGE, PROD_DELETE, CAT_LIST, EMP_RETRIEVE, LOGOUT
	
}
